#!/usr/bin/bash

NODES=8

if [ -z $1 ] || ([ $1 != "show" ] && [ $1 != "on" ] && [ $1 != "off" ])
then
	echo "Usage: interrupt-coalescing {show|on|off}"
	exit
fi


for (( i=$NODES; i>0; i-- ))
do
	case $1 in 
		"show")
			printf "node$i... "
			ssh node$i sudo ethtool --show-coalesce eth0 | grep "Adaptive"
			;;
		"on")
			printf "node$i... "
			ssh node$i sudo ethtool --coalesce eth0 adaptive-rx on
			printf "done\n"
			;;
		"off")
			printf "node$i... "
			ssh node$i sudo ethtool --coalesce eth0 adaptive-rx off
			printf "done\n"
			;;	       
	esac
done

