#!/usr/bin/bash

if [ -z $1 ] || ([ $1 != "openblas-serial" ] && [ $1 != "blis-serial" ] && [ $1 != "openblas-openmp" ] && [ $1 != "blis-openmp" ])
then
	echo "Usage: linpack-hpl-out-sort {openblas-serial|blis-serial|openblas-openmp|blis-openmp}"
	exit
fi

for nb in `seq 32 8 256`
do
	grep WR HPL.out.*\_$nb\_*.$1 | sort -g -k 7 | tail -n 1 | gawk '{ printf "%f,\n", $7 }'
done

