#!/usr/bin/bash

# This script extracts the maximum Gflops from a HPL.out file
# for a particular NB, and then sorts these by NB for plotting.

# Select which BLAS library HPL.out files to sort.
if [[ $1 != "openblas" ]] && [[ $1 != "blis" ]]
then
	echo "Useage: picluster-sort-hpl-out openblas|blis"
	exit
fi

# Loop over all HPL.out files.
for f in HPL.out.*.$1
do
	grep WR $f | sort -g -k 7 | tail -n 1
done | sort -g -k 3 | gawk {'printf("%i %f\n", $3, $7)'}

